backend:
  name: git-gateway
  branch: master

media_folder: 'src/assets/images/uploads' # Folder where user uploaded files should go
public_folder: 'assets/images/uploads'
publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: 'product' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Products' # Used in the UI, ie.: "New Post"
    folder: 'cms/product' # (src/assets/blog) The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Featured Image',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'reference' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'References' # Used in the UI, ie.: "New Post"
    folder: 'cms/reference' # (src/assets/blog) The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }

      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
